# Generated by Django 6.0.5 on 2026-06-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeituraSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turbidez_ntu", models.FloatField(verbose_name="Turbidez (NTU)")),
                ("vazao_ls", models.FloatField(verbose_name="Vazão (L/s)")),
                ("nivel_cm", models.FloatField(verbose_name="Nível (cm)")),
                (
                    "status_conformidade",
                    models.BooleanField(verbose_name="Dentro da Portaria 888?"),
                ),
                (
                    "horario",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Horário da Leitura"
                    ),
                ),
            ],
            options={
                "db_table": "leituras_sigua",
            },
        ),
    ]
