# Generated by Django 6.0.6 on 2026-06-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leiturasensor',
            name='cloro_residual_mgl',
            field=models.FloatField(blank=True, null=True, verbose_name='Cloro Residual Livre (mg/L)'),
        ),
        migrations.AddField(
            model_name='leiturasensor',
            name='coliformes_ufc',
            field=models.FloatField(blank=True, null=True, verbose_name='Coliformes Totais (UFC/100mL)'),
        ),
        migrations.AddField(
            model_name='leiturasensor',
            name='cor_uh',
            field=models.FloatField(blank=True, null=True, verbose_name='Cor Aparente (uH)'),
        ),
        migrations.AddField(
            model_name='leiturasensor',
            name='operador',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='leiturasensor',
            name='ph',
            field=models.FloatField(blank=True, null=True, verbose_name='pH'),
        ),
        migrations.AddField(
            model_name='leiturasensor',
            name='ponto_coleta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ponto de Coleta'),
        ),
    ]
