# Generated by Django 6.0.5 on 2026-06-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoramento", "0002_leiturasensor_cloro_residual_mgl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leiturasensor",
            name="dosagem_aplicada_mgl",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Dosagem de Coagulante Aplicada (mg/L)",
            ),
        ),
        migrations.AddField(
            model_name="leiturasensor",
            name="observacao_operador",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observação do Operador"
            ),
        ),
        migrations.AddField(
            model_name="leiturasensor",
            name="sugestao_aceita",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Operador aceitou a sugestão?"
            ),
        ),
    ]
