# Generated by Django 6.0.6 on 2026-06-12 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_leiturasensor_cloro_residual_mgl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=100, verbose_name='Parâmetro')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('feedback', models.CharField(blank=True, choices=[('aceita', 'Aceita'), ('rejeitada', 'Rejeitada')], max_length=20, null=True, verbose_name='Feedback do Operador')),
                ('operador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Operador')),
                ('horario', models.DateTimeField(auto_now_add=True, verbose_name='Horário')),
                ('leitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes', to='monitoramento.leiturasensor')),
            ],
            options={
                'db_table': 'sugestao_log',
                'ordering': ['-horario'],
            },
        ),
    ]
