# Generated by Django 6.0.5 on 2026-06-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoramento", "0003_add_feedback_operador"),
    ]

    operations = [
        migrations.AddField(
            model_name="leiturasensor",
            name="alcalinidade_bruta",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Alcalinidade Bruta"
            ),
        ),
        migrations.AddField(
            model_name="leiturasensor",
            name="alcalinidade_tratada",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Alcalinidade Tratada"
            ),
        ),
        migrations.AddField(
            model_name="leiturasensor",
            name="cor_bruta_uh",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Cor Bruta (uH)"
            ),
        ),
        migrations.AddField(
            model_name="leiturasensor",
            name="hipoclorito_sodio_kg",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Hipoclorito de Sódio (Kg)"
            ),
        ),
        migrations.AddField(
            model_name="leiturasensor",
            name="ph_bruto",
            field=models.FloatField(blank=True, null=True, verbose_name="pH Bruto"),
        ),
        migrations.AddField(
            model_name="leiturasensor",
            name="policloreto_aluminio_l",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Policloreto de Alumínio (L)"
            ),
        ),
        migrations.AddField(
            model_name="leiturasensor",
            name="sulfato_aluminio_kg",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Sulfato de Alumínio (Kg)"
            ),
        ),
        migrations.AddField(
            model_name="leiturasensor",
            name="turbidez_bruta_ntu",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Turbidez Bruta (NTU)"
            ),
        ),
        migrations.AddField(
            model_name="leiturasensor",
            name="vazao_m3_dia",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Vazão de Entrada (M³/dia)"
            ),
        ),
        migrations.AlterField(
            model_name="leiturasensor",
            name="cor_uh",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Cor Aparente Tratada (uH)"
            ),
        ),
        migrations.AlterField(
            model_name="leiturasensor",
            name="horario",
            field=models.DateTimeField(verbose_name="Horário da Leitura"),
        ),
        migrations.AlterField(
            model_name="leiturasensor",
            name="nivel_cm",
            field=models.FloatField(blank=True, null=True, verbose_name="Nível (cm)"),
        ),
        migrations.AlterField(
            model_name="leiturasensor",
            name="ph",
            field=models.FloatField(blank=True, null=True, verbose_name="pH Tratado"),
        ),
        migrations.AlterField(
            model_name="leiturasensor",
            name="turbidez_ntu",
            field=models.FloatField(verbose_name="Turbidez Tratada (NTU)"),
        ),
        migrations.AlterField(
            model_name="leiturasensor",
            name="vazao_ls",
            field=models.FloatField(blank=True, null=True, verbose_name="Vazão (L/s)"),
        ),
    ]
